spring:
  profiles: default

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://146.148.76.237:9735/senier_project?useSSL=false&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: senier
    password: payment#135
    
  quartz:
    job-store-type: jdbc
    
  http:
    encoding:
      charset: UTF-8
      
server:
  port: 8493